apiVersion: "pipelinesascode.tekton.dev/v1alpha1"
kind: Repository
metadata:
  name: o79ti8m0d-java-quarkus-gitops-repository
spec:
  url: https://github.com/rhtap-rhdh-qe/o79ti8m0d-java-quarkus-gitops